see snoek paper

apply softmax - a point in the probability simplex, i.e. coordinates sum to 1
apply softmax with temperature τ, let τ go to 0 or softmax get less soft - a vertex on simplex

apply sinkhorn - a point in Birkhoff polytope, i.e. double stochastic matrix
apply sinkhorn with temperature - a vertex of Birkhoff polytope, i.e. a permutation matrix

n.b. Hungarian algorithm is used for rounding since can't apply sinkhorn in the limit

In [1]:
import numpy as np

In [70]:
# x = np.arange(9).reshape(3,3)

x = np.array([[42,15,2], [333,666,4], [121,124,125]])

In [71]:
s0 = np.exp(x)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


In [60]:
s0

array([[1.73927494e+018, 3.26901737e+006, 7.38905610e+000],
       [4.16929355e+144, 1.73830087e+289, 5.45981500e+001],
       [3.54513118e+052, 7.12058633e+053, 1.93557604e+054]])

#### on broadcasting for row, col normalization

In [19]:
a =  np.array([[1,1],[2,2]])

In [20]:
a / np.sum(a, axis=1).reshape(2,1) # sum along row, broadcast along row (along dim whose val is 1 i.e. dim=1)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [21]:
a / np.sum(a, axis=0).reshape(1,2) # sum along col, broadcast along col

array([[0.33333333, 0.33333333],
       [0.66666667, 0.66666667]])

In [43]:
def row_norm(x):
    return x / np.sum(x, axis=1).reshape(-1,1)
def col_norm(x):
    return x / np.sum(x, axis=0).reshape(1,-1)

def sums(x):
    print('row sums: {}'.format(np.sum(x, axis=1))) 
    print('col sums: {}'.format(np.sum(x, axis=0))) 

In [62]:
s = col_norm(row_norm(s0))
sums(s)

row sums: [0.98695942 0.79027149 1.2227691 ]
col sums: [1. 1. 1.]


In [65]:
# repeat 
s = col_norm(row_norm(s))
sums(s)



row sums: [0.99200443 0.9089484  1.09904717]
col sums: [1. 1. 1.]
